name: GitHub Actions Learning

on:
  push:
    branches:
      - main

jobs:

  # =====================================
  # JOB 1
  # =====================================

  build:
    runs-on: ubuntu-latest

    steps:

      - name: Step 1
        run: echo "Hello from GitHub Actions"

      - name: Step 2
        run: echo "I am learning CI/CD"

      - name: Step 3
        run: |
          echo "This is my first pipeline"
          echo "Runner is working successfully"

      - name: Create File
        run: |
          echo "This file was created by Job 1" > job1.txt

          echo "Job 1 files:"
          ls -la
      - name: Upload Job 1 File
        uses: actions/upload-artifact@v4
        with:
          name: job1-file
          path: job1.txt


  # =====================================
  # JOB 2
  # =====================================

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:

      - name: Download Job 1 File
        uses: actions/download-artifact@v4
        with:
          name: job1-file

      - name: Check Job 1 File
        run: |
          echo "Job 2 files:"
          ls -la

          echo "Trying to read job1.txt..."

          cat job1.txt