name: First CI

on:
  push:
    branches: [ "main" ]

jobs:
  hello:
    runs-on: self-hosted

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Say hello
        run: echo "GitHub Actions is running!"