name: Terraform Azure CI

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  client-id: ${{ secrets.AZURE_CLIENT_ID }}
  tenant-id: ${{ secrets.AZURE_TENANT_ID }}
  subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  working-directory: ./environments/dev

# concurrency:
#   group: terraform-dev-${{ github.workflow }}
#   cancel-in-progress: true

jobs:
  terraform-job1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ env.client-id }}
          tenant-id: ${{ env.tenant-id }}
          subscription-id: ${{ env.subscription-id }}

      - name: Verify Azure Login
        run: |
          az account show

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Check Terraform Files
        run: |
          pwd
          ls -la
          find . -maxdepth 3 -type f

  terraform-job2: 
    needs: terraform-job1
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        
  terraform-job3: 
    needs: terraform-job2
    runs-on: ubuntu-latest
    steps:
      - name: Terraform Init
        working-directory: ${{ env.working-directory }}
        run: terraform init

  terraform-job4: 
    needs: terraform-job3
    runs-on: ubuntu-latest
    steps:     
      - name: Terraform Validate
        working-directory: ${{ env.working-directory }}
        run: terraform validate

  terraform-job5: 
    needs: terraform-job4
    runs-on: ubuntu-latest
    steps:   
      - name: Terraform Plan
        working-directory: ${{ env.working-directory }}
        run: terraform plan